name: Frontend CI/CD

on:
  push:
    branches:
      - main
env:
  APP_NAME: 'app-frontend'
  PROJECT_ID: 'poc-dev-433917'
  GAR_NAME: 'logger-app'
  GAR_LOCATION: 'europe-central2'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: '${{ env.PROJECT_ID }}'

      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: 'Build and push container'
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.APP_NAME }}:${{ github.sha }}" .
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.APP_NAME }}:${{ github.sha }}"

      - name: 'Send notification'
        uses: 'dawidd6/action-send-mail@v3'
        with:
          server_address: smtp-mail.outlook.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 'Build Completed'
          body: 'Build job of ${{ github.repository }} completed successfully!'
          to: ${{ secrets.EMAIL }}
          from: 'Logger App Workflow'